---
defaults: &defaults
  environment:
    GOOGLE_PROJECT_ID: planet-4-151612
  docker:
    - image: greenpeaceinternational/circleci-base:latest
  working_directory: /home/circleci/app

version: 2

jobs:
  build-push:
    <<: *defaults
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: docker-login.sh
      - run: make build push

workflows:
  version: 2
  branch:
    jobs:
      - build-push:
          context: org-global
          filters:
            branches:
              ignore: develop

  tag:
    jobs:
      - build-push:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
